
site_name: Методические рекомендации для группового проекта
theme:
  name: material

nav:
  - Главная: index.md
  - Введение:
      - О задаче: intro.md
  - Задание по дням:
      - День 1: practice1.md
      - День 2: practice2.md
      - День 3: practice3.md
      - День 4: practice4.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

